import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "entreprise-csf",
    title: "Commande Sans Frontière",
    company: "Commande Sans Frontière",
    kind: "Entreprise",
    year: "2023–2024",
    cover: "/project/csf.png",
    description:
      "Plateforme de transport multimodal (aérien, maritime et routier) offrant des solutions sur mesure pour le commerce international. Plus de 5 ans d'expérience avec livraison rapide et sécurisée depuis la Chine.",
    tags: ["Transport", "E-commerce", "Logistique", "International"],
    links: { site: "https://commandesansfrontiere.com/", repo: "#" },
    region: "CN/NE",
    sector: "Logistics",
  },
  {
    id: "entreprise-ayki",
    title: "AYKI Emploi",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2023",
    cover: "/project/ayki-emploi.png",
    description:
      "Plateforme de recrutement qui connecte les talents aux opportunités. AYKI simplifie le processus en mettant directement en relation les meilleurs candidats avec les entreprises qui recherchent leurs compétences.",
    tags: ["Recrutement", "SaaS", "RH", "Plateforme"],
    links: { site: "https://ayki.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "HR Tech",
  },
  {
    id: "entreprise-ptrniger",
    title: "PTR Niger E-Learning",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2022–2024",
    cover: "/project/ptrniger-elearning.png",
    description:
      "Plateforme e-learning proposant des formations en entrepreneuriat, marketing digital, informatique et plus. Les élèves s'inscrivent et apprennent directement en ligne avec un suivi personnalisé.",
    tags: ["E-learning", "Éducation", "Plateforme", "Formation"],
    links: { site: "https://ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "EdTech",
  },
  {
    id: "entreprise-emmalab",
    title: "EMMA-Lab",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2023",
    cover: "/project/emalab.png",
    description:
      "Laboratoire d'innovation qui accompagne les entrepreneurs et les organisations dans leur transformation digitale et leurs projets innovants. Innover ensemble pour construire l'avenir.",
    tags: ["Innovation", "Digital", "Accompagnement", "Consulting"],
    links: { site: "https://emma-lab.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "Consulting",
  },
  {
    id: "entreprise-lastuce",
    title: "L'Astuce",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2023",
    cover: "/project/lastuce.png",
    description:
      "Communauté d'astuces permettant de découvrir les meilleures techniques avec une communauté passionnée. Conseils pratiques pour améliorer le quotidien : voir les épisodes et proposer ses propres astuces.",
    tags: ["Communauté", "Contenu", "Social", "Plateforme"],
    links: { site: "https://lastuce.ptrniger.com/fr", repo: "#" },
    region: "NE",
    sector: "Media",
  },
  {
    id: "entreprise-clinoo",
    title: "Clinoo+",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2024",
    cover: "/image/clinoo.ptrniger.com.png",
    description:
      "Solution médicale tout-en-un pour cabinets et cliniques : dossier patient électronique, prise de rendez-vous, facturation, documentation clinique et analytique. Plateforme conforme RGPD, déjà adoptée par plus de 1 000 praticiens.",
    tags: ["HealthTech", "SaaS", "Cabinet médical", "RGPD"],
    links: { site: "https://clinoo.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "HealthTech",
  },
  {
    id: "entreprise-jandoo",
    title: "Jandoo",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2024",
    cover: "/image/jandoo.ptrniger.com.png",
    description:
      "Plateforme intelligente de gestion scolaire dédiée à l'enseignement supérieur LMD : structure académique, inscriptions, emplois du temps, absences, notes, scolarité, paie et documents officiels en 9 modules intégrés.",
    tags: ["EdTech", "Gestion scolaire", "LMD", "SaaS"],
    links: { site: "https://jandoo.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "EdTech",
  },
  {
    id: "entreprise-planning",
    title: "Smart Planner",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2024",
    cover: "/image/planning.ptrniger.com.png",
    description:
      "Planificateur boosté à l'IA qui génère automatiquement un emploi du temps sur 14 jours en respectant priorités, contraintes horaires et multi-projets. Suivi par créneaux horaires, alertes de conflits et rythme de travail personnalisable.",
    tags: ["IA", "Productivité", "Planning", "SaaS"],
    links: { site: "https://planning.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "Productivity",
  },
  {
    id: "entreprise-pointage",
    title: "PointageAI",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2024",
    cover: "/image/pointage.ptrniger.com.png",
    description:
      "Système de pointage intelligent par reconnaissance faciale pour l'entreprise. Suivi en temps réel des présences, rapports et statistiques détaillés, et application mobile pour les employés.",
    tags: ["RH", "IA", "Reconnaissance faciale", "SaaS"],
    links: { site: "https://pointage.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "HR Tech",
  },
  {
    id: "entreprise-scholarship",
    title: "ScholarshipNiger",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2024",
    cover: "/image/scholarshipniger.com.png",
    description:
      "Plateforme dédiée aux étudiants nigériens à la recherche de bourses d'études à l'étranger : 500+ bourses actives, 50+ pays partenaires et accompagnement complet pour postuler aux opportunités internationales.",
    tags: ["EdTech", "Bourses", "International", "Plateforme"],
    links: { site: "https://scholarshipniger.com/", repo: "#" },
    region: "NE",
    sector: "EdTech",
  },
  {
    id: "entreprise-wuroobiz",
    title: "Wuroobiz",
    company: "PTR Niger",
    kind: "Entreprise",
    year: "2024",
    cover: "/image/wuroobiz.ptrniger.com.png",
    description:
      "Solution cloud tout-en-un de gestion commerciale pour les PME africaines : point de vente, gestion des stocks, comptabilité, RH, plus de 40 rapports avancés et agent IA WhatsApp intégré.",
    tags: ["ERP", "POS", "Gestion commerciale", "SaaS"],
    links: { site: "https://wuroobiz.ptrniger.com/", repo: "#" },
    region: "NE",
    sector: "Retail",
  },
  {
    id: "entreprise-guidacenter",
    title: "GuidaCenter",
    company: "GuidaCenter",
    kind: "Entreprise",
    year: "2023–2024",
    cover: "/project/guidacenter.png",
    description:
      "Plateforme immobilière moderne qui simplifie l'achat, la vente et la location de biens au Niger. Interface intuitive pour faciliter les transactions immobilières.",
    tags: ["Immobilier", "Plateforme", "E-commerce", "Niger"],
    links: { site: "https://guidacenter.com/", repo: "#" },
    region: "NE",
    sector: "Real Estate",
  },
  {
    id: "freelance-softis",
    title: "Softis Pilates",
    company: "Freelance",
    kind: "Freelance",
    year: "2023",
    cover: "/project/softis.png",
    description:
      "Plateforme complète pour un club sportif de Pilates au Japon. Gestion des cours, réservations, membres et planning pour une expérience utilisateur optimale.",
    tags: ["Sport", "Pilates", "SaaS", "Japon"],
    links: { site: "https://softis.jp/", repo: "#" },
    region: "JP",
    sector: "Sports",
  },
  {
    id: "personnel-icall",
    title: "iCall CRM",
    company: "Projet Personnel",
    kind: "Personnel",
    year: "2022",
    cover: "/project/icall26.png",
    description:
      "Suite CRM complète avec de très nombreuses fonctionnalités : gestion des contacts, suivi des opportunités, automatisation des processus et rapports analytiques. Solution robuste pour la gestion de la relation client.",
    tags: ["CRM", "SaaS", "Gestion", "Entreprise"],
    links: { site: "#", repo: "#" },
    region: "NE",
    sector: "CRM",
  },
  {
    id: "personnel-gestion",
    title: "Gestion Boutique",
    company: "Projet Personnel",
    kind: "Personnel",
    year: "2022",
    cover: "/project/gestion1.png",
    description:
      "Application de gestion de boutique intégrant la gestion des stocks, la comptabilité, le suivi des revenus et les opérations commerciales. Interface simple pour une gestion efficace au quotidien.",
    tags: ["Gestion", "Stocks", "Comptabilité", "POS"],
    links: { site: "#", repo: "#" },
    region: "NE",
    sector: "Retail",
  },
  {
    id: "personnel-shop",
    title: "Shop POS",
    company: "Projet Personnel",
    kind: "Personnel",
    year: "2023",
    cover: "/project/shop.png",
    description:
      "Application de gestion commerciale complète : fournisseurs, comptabilité, achats, QR codes et système POS pour des ventes instantanées. Solution tout-en-un pour la gestion de points de vente.",
    tags: ["POS", "E-commerce", "Gestion", "QR Code"],
    links: { site: "#", repo: "#" },
    region: "NE",
    sector: "Retail",
  },
];
